/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import rsscalelabel.RSScaleLabel;
import Consulta_API.*;
import javax.swing.*;
import Lista.Ingresar_Datos_Lista;
import Lista.Link_URL;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Arbol_avl.*;

/**
 *
 * @author Luis
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     *  albums
        artists
        episodes
        genres
        playlists
        podcasts
        tracks
        users
        multi
     * 
     * 
     * 
     * 
     */
    Consulta Consultar = new Consulta();
    Recolecion_Datos Recolectar =new Recolecion_Datos();
    Ingresar_Datos_Lista Lista = new Ingresar_Datos_Lista();
    Metodo_Cambio_Frame Cambio=new Metodo_Cambio_Frame();
    Link_URL Reproducir=new Link_URL();
    public DefaultListModel<String> modelo= new DefaultListModel<>();
    
    
    public Interfaz() {
        initComponents();
        String Ruta= "C:\\Users\\Luis\\Documents\\NetBeansProjects\\Proyecto-API 2\\Fondo1.1.jpg";
        String Rutarepro= "C:\\Users\\Luis\\Documents\\NetBeansProjects\\Proyecto-API 2\\Boton Reproducir.png";
        String Ruta1= "C:\\Users\\Luis\\Documents\\NetBeansProjects\\Proyecto-API 2\\Fondo1.jpg";
        String Rutalimpiar = "C:\\Users\\Luis\\Documents\\NetBeansProjects\\Proyecto-API 2\\Boton Limpiar.png";
        
        RSScaleLabel.setScaleLabel(Wallpaper, Ruta1);
        RSScaleLabel.setScaleLabel(Walpaper1, Ruta );
        RSScaleLabel.setScaleLabel(Jreproducir, Rutarepro);
        RSScaleLabel.setScaleLabel(JLimpiar, Rutalimpiar);
        
        jTabbedPane1.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false); 
        Jreproducir. setVisible(false);
        JLimpiar.setVisible(false);
        setSize(440, 160);
      //  RSScaleLabel.setScaleLabel(Logotype, Ruta1);
      //  C.Consultar("Nodal", "tracks");
        //r.trasladar_datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jbuscar = new javax.swing.JLabel();
        Jbuscar1 = new javax.swing.JLabel();
        Logotype = new javax.swing.JLabel();
        Jtext_Buscar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Jreproducir = new javax.swing.JLabel();
        JLimpiar = new javax.swing.JLabel();
        Walpaper1 = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("API SPOTIFY");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbuscar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Jbuscar.setForeground(new java.awt.Color(255, 255, 255));
        Jbuscar.setText("BUSCAR:");
        jPanel1.add(Jbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, -1));

        Jbuscar1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Jbuscar1.setForeground(new java.awt.Color(255, 255, 255));
        Jbuscar1.setText("FILTRO:");
        jPanel1.add(Jbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));
        jPanel1.add(Logotype, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 70, 70));

        Jtext_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtext_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Jtext_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, -1));

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(11);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Done", "Sin Filtros", "Albumes", "Artistas", "Episodios", "Generos", "PlayLists", "Podcasts", "Canciones", "Usuarios", "Funcia" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jTabbedPane1.addTab("Albumes", jScrollPane1);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane4.setViewportView(jList2);

        jTabbedPane1.addTab("Artistas", jScrollPane4);

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane5.setViewportView(jList3);

        jTabbedPane1.addTab("Episodios", jScrollPane5);

        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane6.setViewportView(jList4);

        jTabbedPane1.addTab("Generos", jScrollPane6);

        jList7.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jList7);

        jTabbedPane1.addTab("PlayLists", jScrollPane2);

        jList6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane8.setViewportView(jList6);

        jTabbedPane1.addTab("Usuarios", jScrollPane8);

        jList5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane7.setViewportView(jList5);

        jTabbedPane1.addTab("Canciones", jScrollPane7);

        jList8.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(jList8);

        jTabbedPane1.addTab("Podcasts", jScrollPane3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 250));

        jButton1.setText("Reproducir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        Jreproducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JreproducirMouseClicked(evt);
            }
        });
        jPanel1.add(Jreproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 200, 40));

        JLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLimpiarMouseClicked(evt);
            }
        });
        jPanel1.add(JLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, 40));
        jPanel1.add(Walpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 120));

        Wallpaper.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Jtext_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtext_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtext_BuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          String seleccion = (String) jComboBox1.getSelectedItem();
         String Cantidad = (String) jComboBox2.getSelectedItem();
         /* jTabbedPane1.setVisible(true);
          jButton1.setVisible(true);
          jButton2.setVisible(true);
          Walpaper1.setVisible(false);
          setSize(660, 430);*/
          switch(seleccion) {
  case "Sin Filtros":
      Consultar.Consultar(Jtext_Buscar.getText(), "multi",Cantidad);
      Recolectar.trasladar_datos(Consultar.getDate());
      Lista.Ingresar_datos_lista(Recolectar.getCom());
      jTabbedPane1.setSelectedIndex(6);     
    break;
  case "Albumes":
      Consultar.Consultar(Jtext_Buscar.getText(), "albums",Cantidad);
      Recolectar.trasladar_datos(Consultar.getDate());
      Lista.Ingresar_datos_lista(Recolectar.getCom());
      //System.out.println(jTabbedPane1.getSelectedIndex();
      jTabbedPane1.setSelectedIndex(0);
    break;
  case "Artistas":
    Consultar.Consultar(Jtext_Buscar.getText(), "artists",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(1);
    break;
  case "Episodios":
    Consultar.Consultar(Jtext_Buscar.getText(), "episodes",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(2);
    break;
  case "Generos":
    Consultar.Consultar(Jtext_Buscar.getText(), "genres",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(3);
    break;
  case "PlayLists":
    Consultar.Consultar(Jtext_Buscar.getText(), "playlists", Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(4);
    break;
  case "Podcasts":
    Consultar.Consultar(Jtext_Buscar.getText(), "podcasts",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(7);
    break;
  case "Canciones":
    Consultar.Consultar(Jtext_Buscar.getText(), "tracks",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(6);
    break;
  case "Usuarios":
    Consultar.Consultar(Jtext_Buscar.getText(), "users",Cantidad);
    Recolectar.trasladar_datos(Consultar.getDate());
    Lista.Ingresar_datos_lista(Recolectar.getCom());
    jTabbedPane1.setSelectedIndex(5);
    break;
  case "Funcia":
      Cambio.Funcia_metod();
             setVisible(false);
    break;
    
}
          
       jList1.setModel(Lista.getModelo_Album());
       jList2.setModel(Lista.getModelo_Artistas());
       jList3.setModel(Lista.getModelo_Episodios());
       jList4.setModel(Lista.getModelo_Generos());
       jList5.setModel(Lista.getModelo_Canciones());
       jList6.setModel(Lista.getModelo_Usuario());
       jList7.setModel(Lista.getModelo_Playlist());
       jList8.setModel(Lista.getModelo_Podcast());
       
       for(int i=0;i<=100 ;i++){
           jProgressBar1.setValue(i);
       }       
       jTabbedPane1.setVisible(true);
          jButton1.setVisible(true);
          jButton2.setVisible(true);
          Walpaper1.setVisible(false);
          setSize(660, 430);
          
          
          
          //AVLTreeWordGraph graph = new AVLTreeWordGraph(Lista.getRoot());
         // Jreproducir.setVisible(true);
       
        /*  
String Caso_1 ="Sin Filtros"; 
          String Caso_2 ="Albumes"; 
          String Caso_3 ="Artistas"; 
          String Caso_4 ="Episodios"; 
          String Caso_5 ="Generos"; 
          String Caso_6 ="PlayList"; 
          String Caso_7 ="Podcasts"; 
          String Caso_8 ="Canciones"; 
          String Caso_9 ="Usuarios"; 
          String Caso_10 ="Funcia"; 
          
          if(seleccion==Caso_1){
              //Cambio.Funcia_metod();
              //setVisible(false);
              Consultar.Consultar(Jtext_Buscar.getText(), "multi");
          }
          
          if(seleccion==Caso_2){
              Consultar.Consultar(Jtext_Buscar.getText(), "albums");
          }
          
          if(seleccion==Caso_3){
              Consultar.Consultar(Jtext_Buscar.getText(), "artists");
          }
          
          if(seleccion==Caso_4){
              Consultar.Consultar(Jtext_Buscar.getText(), "episodes");
          }
          
          if(seleccion==Caso_5){
              Consultar.Consultar(Jtext_Buscar.getText(), "genres");
          }
          
          if(seleccion==Caso_6){
              Consultar.Consultar(Jtext_Buscar.getText(), "playlists");
          }
          
          if(seleccion==Caso_7){
              Consultar.Consultar(Jtext_Buscar.getText(), "podcasts");
          }
          if(seleccion==Caso_8){
              Consultar.Consultar(Jtext_Buscar.getText(), "tracks");
          }
          
          if(seleccion==Caso_9){
              Consultar.Consultar(Jtext_Buscar.getText(), "users");
          }
          
          if(seleccion==Caso_10){
             // Cambio.Funcia_metod();
             //Funcia2 F =new Funcia2();
             //F.setVisible(true);
             Cambio.Funcia_metod();
             setVisible(false);
          }
          */
    
        
        
        

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
                 //System.out.println(jTabbedPane1.getSelectedIndex()); //este funciona
            // System.out.println(jList1.getSelectedIndex());
            // System.out.println(jList1.getSelectedValuesList());
           // System.out.println(jList1.getSelectedValue());  // este funciona
            int Busqueda= jTabbedPane1.getSelectedIndex();
            switch(Busqueda) {
            case 0 -> Lista.Buscar_Enlace(Busqueda,jList1.getSelectedValue());
            case 1 -> Lista.Buscar_Enlace(Busqueda,jList2.getSelectedValue());
            case 2 -> Lista.Buscar_Enlace(Busqueda,jList3.getSelectedValue());
            case 3 -> Lista.Buscar_Enlace(Busqueda,jList4.getSelectedValue());
            case 4 -> Lista.Buscar_Enlace(Busqueda,jList7.getSelectedValue());
            case 5 -> Lista.Buscar_Enlace(Busqueda,jList6.getSelectedValue());
            case 6 -> Lista.Buscar_Enlace(Busqueda,jList5.getSelectedValue());
            case 7 -> Lista.Buscar_Enlace(Busqueda,jList8.getSelectedValue());
            }
            try {
                
            Reproducir.Enlace_Link(Lista.getURL());
            
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
           
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              Lista.Vaciar_Listas();
              jTabbedPane1.setVisible(false);
              jButton1.setVisible(false);
              jButton2.setVisible(false); 
              Jreproducir. setVisible(false);
              JLimpiar.setVisible(false);
              setSize(440, 160);
              Walpaper1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JreproducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JreproducirMouseClicked
        // TODO add your handling code here:
        System.out.println("Funcia");
        int Busqueda= jTabbedPane1.getSelectedIndex();
            switch(Busqueda) {
            case 0 -> Lista.Buscar_Enlace(Busqueda,jList1.getSelectedValue());
            case 1 -> Lista.Buscar_Enlace(Busqueda,jList2.getSelectedValue());
            case 2 -> Lista.Buscar_Enlace(Busqueda,jList3.getSelectedValue());
            case 3 -> Lista.Buscar_Enlace(Busqueda,jList4.getSelectedValue());
            case 4 -> Lista.Buscar_Enlace(Busqueda,jList7.getSelectedValue());
            case 5 -> Lista.Buscar_Enlace(Busqueda,jList6.getSelectedValue());
            case 6 -> Lista.Buscar_Enlace(Busqueda,jList5.getSelectedValue());
            case 7 -> Lista.Buscar_Enlace(Busqueda,jList8.getSelectedValue());
            }
            try {
            Reproducir.Enlace_Link(Lista.getURL());
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
            
            
    }//GEN-LAST:event_JreproducirMouseClicked

    private void JLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLimpiarMouseClicked

Lista.Vaciar_Listas();

        // TODO add your handling code here:
    }//GEN-LAST:event_JLimpiarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLimpiar;
    private javax.swing.JLabel Jbuscar;
    private javax.swing.JLabel Jbuscar1;
    private javax.swing.JLabel Jreproducir;
    private javax.swing.JTextField Jtext_Buscar;
    private javax.swing.JLabel Logotype;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JLabel Walpaper1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
